# This is the docker-compose file to run Medplum's required background services
# It can be used to quickly run 2 services:
#   1) The Postgres database
#   2) The Redis cache
# You can start all services by running "docker-compose up"
services:
  postgres:
    image: postgres:16
    restart: unless-stopped # for production usage, consider using 'always'
    environment:
      - POSTGRES_USER=medplum
      - POSTGRES_PASSWORD=medplum
    volumes:
      - ./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf
      - ./postgres/:/docker-entrypoint-initdb.d/
      - medplum-postgres-data:/var/lib/postgresql/data
    command: postgres -c config_file=/usr/local/etc/postgres/postgres.conf
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    restart: unless-stopped # for production usage, consider using 'always'
    command: redis-server --requirepass medplum
    ports:
      - '6379:6379'

volumes:
  medplum-postgres-data:
