{{- if eq .Values.global.cloudProvider "gcp" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "medplum.fullname" . }}
  namespace: {{ include "medplum.namespace" . }}
  labels:
    {{- include "medplum.labels" . | nindent 4 }}
  annotations:
    ingressClassName: "gce"
    kubernetes.io/ingress.global-static-ip-name: medplum-external-ip
    networking.gke.io/managed-certificates: {{ include "medplum.fullname" . }}
    networking.gke.io/v1beta1.FrontendConfig: {{ include "medplum.fullname" . }}
    cloud.google.com/backend-config: '{"ports": { "8103":"medplum-backendconfig" }}'
spec:
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "medplum.fullname" . }}-service
                port:
                  number: {{ .Values.global.service.port }}
{{- end }}